/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;







/**
 *
 * @author DAVID
 */
public class sistema extends javax.swing.JFrame {
    
   conexionSQL cc=new conexionSQL();
   Connection con=cc.conexion();

    /**
     * Creates new form sistema
     */
    public sistema() {
        initComponents();
        
       this.setLocationRelativeTo(null);
       this.getContentPane().setBackground(getBackground());
       mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbmateria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtcalificacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbestatus = new javax.swing.JComboBox<>();
        btnuevo = new javax.swing.JButton();
        btguardar = new javax.swing.JButton();
        bteliminar = new javax.swing.JButton();
        btactualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaalumno = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        jLabel3.setText("Materia");

        cbmateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATEMATICAS", "ESPAÑOL", "INGLES", "GEOGRAFIA" }));

        jLabel4.setText("Calificación");

        txtcalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalificacionActionPerformed(evt);
            }
        });

        jLabel5.setText("Estatus");

        cbestatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "APROBADO", "REPROBADO", " ", " " }));

        btnuevo.setText("Nuevo");
        btnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuevoActionPerformed(evt);
            }
        });

        btguardar.setText("Guardar");
        btguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguardarActionPerformed(evt);
            }
        });

        bteliminar.setText("Eliminar");
        bteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarActionPerformed(evt);
            }
        });

        btactualizar.setText("Actualizar");
        btactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btactualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcalificacion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombre)
                            .addComponent(txtapellidos)
                            .addComponent(cbmateria, 0, 212, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbestatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnuevo)
                .addGap(18, 18, 18)
                .addComponent(btguardar)
                .addGap(18, 18, 18)
                .addComponent(bteliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btactualizar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtcalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbestatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuevo)
                    .addComponent(btguardar)
                    .addComponent(bteliminar)
                    .addComponent(btactualizar))
                .addGap(21, 21, 21))
        );

        tablaalumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaalumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaalumnoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaalumno);

        jLabel6.setText("informacion de la tabla ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(140, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtcalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalificacionActionPerformed

    private void btnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuevoActionPerformed
       limpiarcajas();
    }//GEN-LAST:event_btnuevoActionPerformed

    private void bteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarActionPerformed
eliminarRegistros();
mostrarDatos();
limpiarcajas();
    }//GEN-LAST:event_bteliminarActionPerformed

    private void btguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguardarActionPerformed

insertarDatos();
limpiarcajas();
mostrarDatos();
    }//GEN-LAST:event_btguardarActionPerformed

    private void tablaalumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaalumnoMouseClicked
    int filaSeleccionada=tablaalumno.rowAtPoint(evt.getPoint());
        
        txtnombre.setText(tablaalumno.getValueAt(filaSeleccionada,1).toString());
        txtapellidos.setText(tablaalumno.getValueAt(filaSeleccionada,2).toString());
        cbmateria.setSelectedItem(tablaalumno.getValueAt(filaSeleccionada, 3));
        txtcalificacion.setText(tablaalumno.getValueAt(filaSeleccionada,4).toString());
        cbestatus.setSelectedItem(tablaalumno.getValueAt(filaSeleccionada,5).toString());
    }//GEN-LAST:event_tablaalumnoMouseClicked

    private void btactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btactualizarActionPerformed
       
        actualizardatos();
        limpiarcajas();
        mostrarDatos();
        
        
    }//GEN-LAST:event_btactualizarActionPerformed
 public void insertarDatos(){
    
       
//insert>>>crear         
        
         
         try {
            String SQL ="insert into  alumnos (nombre,apellidos,materia,calificacion,estatus) values (?,?,?,?,?)";
                
          PreparedStatement pst =con.prepareStatement (SQL);
          pst.setString(1,txtnombre.getText());
          pst.setString(2,txtapellidos.getText());
          
          int seleccionado=cbmateria.getSelectedIndex();
          pst.setString(3, cbmateria.getItemAt(seleccionado));
          
          pst.setDouble(4, Double.parseDouble(txtcalificacion.getText()));
          
          int seleccionado1=cbestatus.getSelectedIndex();
          pst.setString(5, cbestatus.getItemAt(seleccionado1));
        
          
      pst.execute();
       JOptionPane.showMessageDialog(null,"registro exitoso" );   
       
          
           
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"error al registrar datos" + e.getMessage());
        }
                 
    }
    
    public void actualizardatos(){
    
       
//UPDATE >>ACTUALIZAR         
        
         
         try {
            String SQL ="update  alumnos set nombre=?,apellidos=?,materia=?,calificacion=?,estatus=? where idalumnos=?";
            
            
           int filacelecioanada   = tablaalumno.getSelectedRow();
            String dao =(String)tablaalumno.getValueAt(filacelecioanada, 0);
          PreparedStatement pst =con.prepareStatement (SQL);
          pst.setString(1,txtnombre.getText());
          pst.setString(2,txtapellidos.getText());
          
          int seleccionado=cbmateria.getSelectedIndex();
          pst.setString(3, cbmateria.getItemAt(seleccionado));
          
          pst.setDouble(4, Double.parseDouble(txtcalificacion.getText()));
          
          int seleccionado1=cbestatus.getSelectedIndex();
          pst.setString(5, cbestatus.getItemAt(seleccionado1));
        
      pst.setString(6, dao);
      pst.execute();
       JOptionPane.showMessageDialog(null,"registro exitoso" );   
       
          
           
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"error al registrar datos" + e.getMessage());
        }
                 
    }
    public void mostrarDatos(){
    
        String [] titulos={"ID","Nombre","Apellidos","Materia","calificacion","Estatus"};
         String [] registros =new String[6];
    
         DefaultTableModel modelo=new DefaultTableModel  (null,titulos);  
//read>>>selet         
         String SQL ="select *from alumnos";
         
         try {
            Statement st=con.createStatement();
             ResultSet rs=st.executeQuery(SQL);
                
          while (rs.next()){
          registros [0]=rs.getString("idalumnos");
          registros [1]=rs.getString("nombre");
          registros [2]=rs.getString("apellidos");
          registros [3]=rs.getString("materia");
          registros [4]=rs.getString("calificacion");
          registros [5]=rs.getString("estatus");
          
          modelo.addRow(registros);
          
          }
           tablaalumno.setModel(modelo);
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"error al mostrar datos" + e.getMessage());
        }
                 
    }
    public void eliminarRegistros(){
        
        int filaSeleccioanda =tablaalumno.getSelectedRow();
        
        try {
  
//>>>delete           
            String SQL="delete from alumnos where idalumnos="+tablaalumno.getValueAt(filaSeleccioanda,0);
            
            Statement st=con.createStatement();
            
            int n=st.executeUpdate(SQL);
            
            if (n>0){
            
            JOptionPane.showMessageDialog(null,"registro eliminado" );
            }
            
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"error al  eliminar registro" + e.getMessage());
        }
    
    }  
    public void limpiarcajas(){
txtnombre.setText("");
txtapellidos.setText("");
txtcalificacion.setText("");
cbmateria.setSelectedItem(null);
cbestatus.setSelectedItem(null);

}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btactualizar;
    private javax.swing.JButton bteliminar;
    private javax.swing.JButton btguardar;
    private javax.swing.JButton btnuevo;
    private javax.swing.JComboBox<String> cbestatus;
    private javax.swing.JComboBox<String> cbmateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaalumno;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcalificacion;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
//34.41//